# Generated by Django 2.2 on 2019-04-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('usersex', models.CharField(max_length=2)),
                ('institution', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('userage', models.IntegerField(max_length=20)),
                ('type', models.BooleanField(max_length=2)),
                ('address', models.TextField(max_length=200)),
                ('tel', models.CharField(max_length=20)),
            ],
        ),
    ]
